name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-west-2
  FRONTEND_REPO_URI: ${{ secrets.FRONTEND_REPO_URI }}
  BACKEND_REPO_URI: ${{ secrets.BACKEND_REPO_URI }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: aws-actions
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build and Push Frontend Docker Image to ECR
      - name: Build and Push Frontend
        run: |
          docker build -t frontend-app .
          docker tag frontend-app:latest ${{ secrets.FRONTEND_REPO_URI }}:latest
          docker push ${{ secrets.FRONTEND_REPO_URI }}:latest

      # Build and Push Backend Docker Image to ECR
      - name: Build and Push Backend
        run: |
          docker build -t backend-app ./ELP_PATH_BE
          docker tag backend-app:latest ${{ secrets.BACKEND_REPO_URI }}:latest
          docker push ${{ secrets.BACKEND_REPO_URI }}:latest

      # Deploy ECS Service Update for Frontend
      - name: Update Frontend ECS Service
        run: |
          aws ecs update-service --cluster my-cluster --service frontend-service --force-new-deployment

      # Deploy ECS Service Update for Backend
      - name: Update Backend ECS Service
        run: |
          aws ecs update-service --cluster my-cluster --service backend-service --force-new-deployment

