name: Deploy to AWS

on:
  push:
    branches:
      - main  # Set your preferred branch for deployment (e.g., main or master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws-actions

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Set your AWS region

    # Step 3: Install MySQL Client
    - name: Install MySQL Client
      run: sudo apt-get install mysql-client -y  # Install MySQL client for running queries

    # Step 4: Initialize MySQL Database
    # - name: Initialize MySQL Database
    #   run: |
    #     echo "Waiting for the RDS MySQL instance to be available..."
    #     sleep 60  # Wait for DB to initialize (adjust as necessary)
        
    #     # Assuming the RDS instance is created and accessible, we run the SQL script via RDS or Lambda
    #     RDS_ENDPOINT=$(aws rds describe-db-instances --query "DBInstances[?DBInstanceIdentifier=='terraform-20250108083208118700000001'].Endpoint.Address" --output text)
    #     mysql -h $RDS_ENDPOINT -u root -p${{ secrets.RDS_DB_PASSWORD }} mydb < ./ELP_PATH_DB/elp_path_db_16.sql
    #     echo "Database initialization complete!"

    # Step 5: Deploy ECS Service for Frontend
    - name: Deploy ECS frontend service
      run: |
        echo "Updating ECS Frontend Service..."
        FRONTEND_TASK_DEFINITION_ARN=${{ secrets.FRONTEND_TASK_DEFINITION_ARN }}
        aws ecs update-service --cluster my-ecs-cluster --service frontend-service --task-definition $FRONTEND_TASK_DEFINITION_ARN

    # Step 6: Deploy ECS Service for Backend
    - name: Deploy ECS backend service
      run: |
        echo "Updating ECS Backend Service..."
        BACKEND_TASK_DEFINITION_ARN=${{ secrets.BACKEND_TASK_DEFINITION_ARN }}
        aws ecs update-service --cluster my-ecs-cluster --service backend-service --task-definition $BACKEND_TASK_DEFINITION_ARN

    # Step 7: Verify ECS services are running
    - name: Verify ECS services
      run: |
        aws ecs describe-services --cluster my-ecs-cluster --services frontend-service backend-service
